// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncIT.Web.Database;

#nullable disable

namespace SyncIT.Web.Database.Migrations
{
    [DbContext(typeof(SyncItContext))]
    [Migration("20251106172359_AddLastUsedTime")]
    partial class AddLastUsedTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalDbGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Members")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OverwriteName")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdditionalGroups");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalDbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OverwriteCid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverwriteFirstName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverwriteLastName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverwriteNick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverwriteRecoveryEmail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecoveryEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdditionalUsers");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.Services.BaseSyncServiceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAsSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAsTarget")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaseSyncServiceConfigs");

                    b.HasDiscriminator().HasValue("BaseSyncServiceConfig");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.Services.GSuiteServiceConfig", b =>
                {
                    b.HasBaseType("SyncIT.Web.Database.Models.Services.BaseSyncServiceConfig");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendNewUserEmail")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("GSuiteServiceConfig");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.Services.GammaServiceConfig", b =>
                {
                    b.HasBaseType("SyncIT.Web.Database.Models.Services.BaseSyncServiceConfig");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("GammaServiceConfig");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.Services.JsonServiceConfig", b =>
                {
                    b.HasBaseType("SyncIT.Web.Database.Models.Services.BaseSyncServiceConfig");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.ToTable("BaseSyncServiceConfigs", t =>
                        {
                            t.Property("IsReadOnly")
                                .HasColumnName("JsonServiceConfig_IsReadOnly");
                        });

                    b.HasDiscriminator().HasValue("JsonServiceConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
