// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncIT.Web.Database;

#nullable disable

namespace SyncIT.Web.Database.Migrations
{
    [DbContext(typeof(SyncItContext))]
    partial class SyncItContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalGroup", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("AdditionalGroups", (string)null);
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalGroupAlias", b =>
                {
                    b.Property<string>("GroupEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalGroupEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupEmail", "AliasEmail");

                    b.HasIndex("AdditionalGroupEmail");

                    b.ToTable("AdditionalGroupAliases", (string)null);
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalGroupMember", b =>
                {
                    b.Property<string>("GroupEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalGroupEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupEmail", "MemberEmail");

                    b.HasIndex("AdditionalGroupEmail");

                    b.ToTable("AdditionalGroupMembers", (string)null);
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalUser", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("AdditionalUsers", (string)null);
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalUserAlias", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalUserEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("UserEmail", "AliasEmail");

                    b.HasIndex("AdditionalUserEmail");

                    b.ToTable("AdditionalUserAliases", (string)null);
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.Services.BaseSyncServiceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaseSyncServiceConfigs", (string)null);

                    b.HasDiscriminator().HasValue("BaseSyncServiceConfig");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.Services.GSuiteServiceConfig", b =>
                {
                    b.HasBaseType("SyncIT.Web.Database.Models.Services.BaseSyncServiceConfig");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendNewUserEmail")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("GSuiteServiceConfig");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.Services.GammaServiceConfig", b =>
                {
                    b.HasBaseType("SyncIT.Web.Database.Models.Services.BaseSyncServiceConfig");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("GammaServiceConfig");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.Services.JsonServiceConfig", b =>
                {
                    b.HasBaseType("SyncIT.Web.Database.Models.Services.BaseSyncServiceConfig");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.ToTable("BaseSyncServiceConfigs", null, t =>
                        {
                            t.Property("IsReadOnly")
                                .HasColumnName("JsonServiceConfig_IsReadOnly");
                        });

                    b.HasDiscriminator().HasValue("JsonServiceConfig");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalGroupAlias", b =>
                {
                    b.HasOne("SyncIT.Web.Database.Models.AdditionalGroup", null)
                        .WithMany("Aliases")
                        .HasForeignKey("AdditionalGroupEmail");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalGroupMember", b =>
                {
                    b.HasOne("SyncIT.Web.Database.Models.AdditionalGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("AdditionalGroupEmail");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalUserAlias", b =>
                {
                    b.HasOne("SyncIT.Web.Database.Models.AdditionalUser", null)
                        .WithMany("Aliases")
                        .HasForeignKey("AdditionalUserEmail");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalGroup", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("SyncIT.Web.Database.Models.AdditionalUser", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
